import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react';
import Navbar from '../app/components/Navbar';
import Footer from '../app/components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mie Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
        <Navbar />
          <main>{children}</main>
          <Footer />
      </body>
    </html>
  
  );
}
